output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

filebeat.inputs:
  - type: mqtt
    hosts:
      - app:1883
    topics:
      - INFO
      - BID
      -
      - OFFER
    tags: ["json"]
    enabled: true
    fields:
      event.dataset: market-data
      event.module: filebeat-mqtt
    pipeline: filebeat-mqtt-pipeline
    index: "%{[agent.name]}-mqtt-%{+yyyy.MM.dd}"
#Set this as the pipeline inside elk
#[
#  {
#    "json": {
#      "field": "message",
#      "add_to_root": true
#    }
#  }
#]
