output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

filebeat.inputs:
  - type: mqtt
    hosts:
      - mosquitto:1883
    topics:
      - INFO
      - open-elecbay/info
    tags: ["json"]
    enabled: true
    fields:
      event.dataset: market-data
      event.module: filebeat-mqtt
    pipeline: filebeat-mqtt-pipeline
    index: "%{[agent.name]}-mqtt-messages-%{+yyyy.MM.dd}"
  - type: mqtt
    hosts:
      - mosquitto:1883
    topics:
      - METRICS
      - open-elecbay/metrics
    tags: ["json"]
    enabled: true
    fields:
      event.dataset: market-data
      event.module: filebeat-mqtt
    pipeline: filebeat-mqtt-pipeline
    index: "%{[agent.name]}-mqtt-metrics-%{+yyyy.MM.dd}"
